language: c

os:
  - linux
branches:
  only:
    - master
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
script:
  - cd  ~/build/huskyproject/huskylib
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/hptzip
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cpack
